// Centralized error codes for consistency
const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',
  SESSION_SECURITY_VIOLATION: 'SESSION_SECURITY_VIOLATION',
  SESSION_ERROR: 'SESSION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // User Management
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  DUPLICATE_USER: 'DUPLICATE_USER',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  
  // Posts
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_CREATION_FAILED: 'POST_CREATION_FAILED',
  POST_UPDATE_FAILED: 'POST_UPDATE_FAILED',
  POST_DELETE_FAILED: 'POST_DELETE_FAILED',
  
  // Comments
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_CREATION_FAILED: 'COMMENT_CREATION_FAILED',
  COMMENT_UPDATE_FAILED: 'COMMENT_UPDATE_FAILED',
  COMMENT_DELETE_FAILED: 'COMMENT_DELETE_FAILED',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

module.exports = ERROR_CODES;